version: "3.9"

services:
  roundipy:
    build: .
    image: roundipy-img
    container_name: roundipy
    restart: unless-stopped
    environment:
      ROUNDIPY_JOBS: 2
      TTL_SECONDS: 60
      MAX_CLIP_SECONDS: 60
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      roundipy_net:
        ipv4_address: 10.77.0.10

networks:
  roundipy_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.77.0.0/24